In [2]:
import pandas as pd
from IPython.display import display

In [14]:
stock_prices=pd.read_csv("stock_prices.csv")
stock_prices.head(25)

,Unnamed: 0,symbol,date,adjusted_date,close,adjusted_date_one_year_later,close_one_year_later
0,0,GPOR,2023-12-31,2024-01-02,134.09,2024-12-30,181.50
1,1,FIHL,2023-12-31,2024-01-02,12.33,2024-12-30,17.73
2,2,CALM,2023-06-03,2023-06-05,47.09,2024-06-03,61.12
3,3,APA,2023-12-31,2024-01-02,36.11,2024-12-30,22.42
4,4,FINV,2023-12-31,2024-01-02,4.82,2024-12-30,6.80
5,5,SPNT,2023-12-31,2024-01-02,11.51,2024-12-30,14.20
6,6,LNG,2023-12-31,2024-01-02,169.41,2024-12-30,213.07
7,7,CEIX,2023-12-31,2024-01-02,101.13,2024-12-30,105.96
8,8,NOG,2023-12-31,2024-01-02,36.84,2024-12-30,36.58
9,9,CVI,2023-12-31,2024-01-02,31.15,2024-12-30,18.56
10,10,ARLP,2023-12-31,2024-01-02,21.16,2024-12-30,25.89
11,11,TRMD,2023-12-31,2024-01-02,31.45,2024-12-30,19.00
12,12,INSW,2023-12-31,2024-01-02,46.59,2024-12-30,35.15
13,13,FMC,2023-12-31,2024-01-02,64.84,2024-12-30,48.45
14,14,AMR,2023-12-31,2024-01-02,341.24,2024-12-30,201.11
15,15,BWLP,2023-12-31,2024-01-02,15.30,2024-12-30,11.04
16,16,OGN,2023-12-31,2024-01-02,14.71,2024-12-30,14.64
17,17,PBF,2023-12-31,2024-01-02,44.40,2024-12-30,25.57
18,18,HAFN,2023-12-31,2024-01-02,NaN,2024-12-30,5.44
19,19,AGO,2023-12-31,2024-01-02,74.67,2024-12-30,89.37
20,20,HG,2023-12-31,2024-01-02,15.03,2024-12-30,18.90
21,21,CPE,2023-12-31,2024-01-02,32.57,2024-12-30,NaN
22,22,ERF,2023-12-31,2024-01-02,15.27,2024-12-30,NaN
23,23,ADX,2023-12-31,2024-01-02,17.45,2024-12-30,20.30
24,24,LBRT,2023-12-31,2024-01-02,18.16,2024-12-30,19.67

In [15]:
stock_prices["yield_rate"]=stock_prices["close_one_year_later"]/stock_prices["close"]-1
stock_prices.head(25)

,Unnamed: 0,symbol,date,adjusted_date,close,adjusted_date_one_year_later,close_one_year_later,yield_rate
0,0,GPOR,2023-12-31,2024-01-02,134.09,2024-12-30,181.50,0.353568
1,1,FIHL,2023-12-31,2024-01-02,12.33,2024-12-30,17.73,0.437956
2,2,CALM,2023-06-03,2023-06-05,47.09,2024-06-03,61.12,0.297940
3,3,APA,2023-12-31,2024-01-02,36.11,2024-12-30,22.42,-0.379119
4,4,FINV,2023-12-31,2024-01-02,4.82,2024-12-30,6.80,0.410788
5,5,SPNT,2023-12-31,2024-01-02,11.51,2024-12-30,14.20,0.233710
6,6,LNG,2023-12-31,2024-01-02,169.41,2024-12-30,213.07,0.257718
7,7,CEIX,2023-12-31,2024-01-02,101.13,2024-12-30,105.96,0.047760
8,8,NOG,2023-12-31,2024-01-02,36.84,2024-12-30,36.58,-0.007058
9,9,CVI,2023-12-31,2024-01-02,31.15,2024-12-30,18.56,-0.404173
10,10,ARLP,2023-12-31,2024-01-02,21.16,2024-12-30,25.89,0.223535
11,11,TRMD,2023-12-31,2024-01-02,31.45,2024-12-30,19.00,-0.395866
12,12,INSW,2023-12-31,2024-01-02,46.59,2024-12-30,35.15,-0.245546
13,13,FMC,2023-12-31,2024-01-02,64.84,2024-12-30,48.45,-0.252776
14,14,AMR,2023-12-31,2024-01-02,341.24,2024-12-30,201.11,-0.410649
15,15,BWLP,2023-12-31,2024-01-02,15.30,2024-12-30,11.04,-0.278431
16,16,OGN,2023-12-31,2024-01-02,14.71,2024-12-30,14.64,-0.004759
17,17,PBF,2023-12-31,2024-01-02,44.40,2024-12-30,25.57,-0.424099
18,18,HAFN,2023-12-31,2024-01-02,NaN,2024-12-30,5.44,NaN
19,19,AGO,2023-12-31,2024-01-02,74.67,2024-12-30,89.37,0.196866
20,20,HG,2023-12-31,2024-01-02,15.03,2024-12-30,18.90,0.257485
21,21,CPE,2023-12-31,2024-01-02,32.57,2024-12-30,NaN,NaN
22,22,ERF,2023-12-31,2024-01-02,15.27,2024-12-30,NaN,NaN
23,23,ADX,2023-12-31,2024-01-02,17.45,2024-12-30,20.30,0.163324
24,24,LBRT,2023-12-31,2024-01-02,18.16,2024-12-30,19.67,0.083150

In [11]:
# Extract the year from the 'date' column
stock_prices['year'] = pd.to_datetime(stock_prices['adjusted_date']).dt.year

# Calculate the average yield rate for each year
average_yield_per_year = stock_prices.groupby('year')['yield_rate'].mean().reset_index()

In [12]:
display(average_yield_per_year)

    year  yield_rate
0   2001         NaN
1   2004         NaN
2   2005         NaN
3   2006   -0.045744
4   2007    0.113063
5   2008   -0.962938
6   2011         NaN
7   2012    0.332771
8   2013    0.105337
9   2014   -0.146336
10  2015    0.074822
11  2016    0.065400
12  2017    0.540237
13  2018   -0.112936
14  2019    0.040903
15  2020    0.403629
16  2021   -0.029757
17  2022    0.863514
18  2023    0.239501
19  2024   -0.019790

In [16]:
average_yield_per_year.to_csv("yearly_yield.csv")